version: "3.9"

services:

  frontend:
    build: ./frontend
    image: nigredo
    container_name: frontend
    restart: unless-stopped

    volumes: 
      - ./frontend:/app

    depends_on: 
      - database
      
  admin:
    build: ./admin
    image: citrinitas
    container_name: admin
    restart: unless-stopped

    volumes: 
      - ./admin:/app

    depends_on: 
      - database
  
  backend:
    build: ./backend
    image: albedo
    container_name: backend
    restart: unless-stopped

    volumes: 
      - ./backend/storage:/storage
    
    env_file: 
      - postgres.env
      - backend/backend.env

    depends_on: 
      - database

  database:
    image: postgres:13-alpine
    restart: unless-stopped

    env_file: 
      - postgres.env

    ports: 
      - "5432:5432"

  session_store:
    image: postgres:13-alpine
    restart: unless-stopped

    env_file: 
      - postgres.env

  caddy:
    image: caddy:alpine
    restart: unless-stopped

    volumes:
      - ./caddy:/etc/caddy
      - ./caddy/data:/data

    ports:
      - "80:80"
      - "443:443"
