version: "3.9"

services:
  backend:
    build: ./backend
    image: albedo
    restart: unless-stopped

    volumes: 
      - ./backend:/app
      - ./backend/storage:/storage
    
    command: air
    
    env_file: 
      - postgres.env
      - backend/backend.env

    depends_on: 
      - database

  admin:
    build: ./admin
    image: citrinitas
    restart: unless-stopped

    command: npm run serve

    ports:
      - "8080:8080"

    volumes: 
      - ./admin:/app

    depends_on: 
      - database

  caddy:
    image: caddy:alpine
    restart: unless-stopped

    volumes:
      - ./caddy/dev:/etc/caddy
      - ./caddy/data:/data

    ports:
      - "80:80"
      - "443:443"

  database:
    image: postgres:13-alpine
    restart: unless-stopped

    env_file: 
      - postgres.env

    ports: 
      - "5432:5432"

    volumes:
      - dev-database:/var/lib/postgresql/data

  session_store:
    image: postgres:13-alpine
    restart: unless-stopped

    env_file: 
      - postgres.env

    volumes:
      - dev-session:/var/lib/postgresql/data

volumes:
  dev-database:
  dev-session: