FROM golang:1.16-alpine as builder

RUN apk add build-base

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY ./ ./

RUN go build -o ./app .
RUN ls -la 

FROM alpine

ENV PROD=1

WORKDIR /app
COPY --from=builder /app/app ./

RUN ls -la /app

CMD ["./app"]