### Setup: (VSCode) Add something like
# "rest-client.environmentVariables": {
#		"$shared": {
#			"session_id": "f7c5bb56-08eb-4af6-9b07-eae7a92be157"
#		}
#	},
# to your .vscode/settings.json file.

# Get self
GET https://localhost/api/v1/self
Cookie: session_id={{session_id}}

###

# Get Users
GET https://localhost/api/v1/users
Cookie: session_id={{session_id}}

###

# Get Tournaments
GET https://localhost/api/v1/tournaments
Cookie: session_id={{session_id}}

###

# Get Tournament
GET https://localhost/api/v1/tournaments/1
Authorization: Bearer {{session_id}}

###

# Delete Tournament
DELETE https://localhost/api/v1/tournaments/1
Cookie: session_id={{session_id}}
content-type: application/json

###

# Post Tournament
POST https://localhost/api/v1/tournaments
Cookie: session_id={{session_id}}
content-type: application/json

{
    "name":"Tournament 1",
    "description":"This is a tournament",
    "download_path":"https://google.com",
    "start_time":"2022-10-02T15:00:00Z",
    "end_time":"2022-10-10T15:00:00Z",
    "registration_start_time": "2021-09-01T00:00:00Z",
    "registration_end_time": "2022-10-01T23:59:59Z"
}

###

# Update Tournament
PUT https://localhost/api/v1/tournaments/1
Cookie: session_id={{session_id}}
content-type: application/json

{
    "name":"Tournament 1",
    "description":"This is an updated tournament",
    "download_path":"https://google.com",
    "start_time":"2022-10-02T15:00:00Z",
    "end_time":"2022-10-10T15:00:00Z"
}

###

# Post Round
POST https://localhost/api/v1/tournaments/1/rounds
Cookie: session_id={{session_id}}
content-type: application/json

{
    "name":"Grandfinals",
    "description":"This is a tournament",
    "download_path":"https://google.com",
    "start_time":"2022-10-02T15:00:00Z",
    "end_time":"2022-10-10T15:00:00Z"
}

### 

# Activate Round
POST https://localhost/api/v1/tournaments/1/rounds/activate
Cookie: session_id={{session_id}}
content-type: application/json

{
    "Name": "Grandfinals"
}


###

# Add Staff
POST https://localhost/api/v1/tournaments/1/staff
Cookie: session_id={{session_id}}
Content-Type: application/json

{
    "user_id": 1,
    "role": "judge"
}

###

# Register User
POST https://localhost/api/v1/tournaments/1/registration
Cookie: session_id={{session_id}}
Content-Type: application/json


###

# Unregister User
DELETE https://localhost/api/v1/tournaments/1/registration
Cookie: session_id={{session_id}}
Content-Type: application/json

### 

# Get Beatmaps
GET https://localhost/api/v1/tournaments/1/rounds/Grandfinals/beatmaps
Cookie: session_id={{session_id}}
Content-Type: application/json

### 

# Post BeatmapSubmittion
POST https://localhost/api/v1/tournaments/1/rounds/Grandfinals/beatmaps
Cookie: session_id={{session_id}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="main.go"

< /home/dev/Desktop/test.osu
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Delete BeatmapSubmittion
DELETE https://localhost/api/v1/tournaments/1/rounds/Grandfinals/beatmaps/1
Authorization: Bearer {{session_id}}