### Setup: (VSCode) Add something like
# "rest-client.environmentVariables": {
#		"$shared": {
#			"session_id": "f7c5bb56-08eb-4af6-9b07-eae7a92be157"
#		}
#	},
# to your .vscode/settings.json file.

# Get self
GET https://localhost/api/v1/self
Cookie: session_id={{session_id}}

###

# Get Tournaments
GET https://localhost/api/v1/tournaments
Cookie: session_id={{session_id}}

###

# Post Tournament
POST https://localhost/api/v1/tournaments
Cookie: session_id={{session_id}}
content-type: application/json

{
    "name":"Tournament 1",
    "description":"This is a tournament",
    "download_path":"https://google.com",
    "start_time":"2021-10-02T15:00:00Z",
    "end_time":"2021-10-10T15:00:00Z"
}